# 예외 처리
### Kotlin의 예외
구조
- Throwable
   - Error: 시스템에 비정상적인 예외. 예측이 어렵고 복구가 불가능하다
      - Unchecked errors: StackOverflowError, OutOfMemoryError, InternalError, UnknownError
   - Exception: 시스템에서 포착 가능하여 (try-catch) 복구 가능. 예외처리 강제
      - RuntimeException: 런타임시에 발생하는 에러. 
         - Unchecked exceptions
      - Checked exceptions

코틀린에서는 Checked exception에 예외 처리를 강제하지 않는다

try-catch도 표현식이기 때문에 값을 받을 수 있다
```kotlin
val a = try {
        "1111".toInt()
    } catch (e: Exception) {
        println("에러 발생")
    }
```

Nothing 타입
- 항상 예외를 리턴한다는 것을 의미
   ```kotlin
   fun fastFail(message: String): Nothing {
      throw IllegalArgumentException(message)
   }
   ```
- elvis 연산자와 함께 쓰면 nullable type을 nonnull 타입으로 변경할 수 있다
   ```kotin
    val nullable: String? = null
    val nonnull: String = nullable ?: fastFail("is null")
    println(nonnull)
   ```

### use 
자바에서 try-withResource 처럼, use 구문 내에서 작업을 수행하고 완료시점에 자원을 해제한다.
```kotlin
FileWriter("test.txt")
      .use {
         it.write("Hello, Kotlin")
      }
```

### run-catching
runCatching을 이용하면 예외에 대한 처리를 해줄 수 있다

함수
- getOrElse
   - 예외가 발생했을 때, 다른 값을 리턴할 수 있도록 한다
      ```kotlin
      // 에러 메시지를 출력하고
      // 기본 값 리턴
      val result = runCatching { getStr() }
           .getOrElse {
               println(it.message)
               "기본 값"
           }
      ```
- getOrNull
   - 예외가 발생하면 null을 리턴한다
      ```kotlin
      // null 리턴
      val result2 = runCatching { getStr() }
        .getOrNull()
      ```
- exceptionOrNull
   - 예외가 발생하면 예외, 예외가 발생하지 않으면 null 반환
      ```kotlin
      // throwable 리턴
      val result3 = runCatching { getStr() }
        .exceptionOrNull()
      ```
- getOrDefault
   - 예외가 발생하면 기본값을 리턴한다
      ```kotlin
      // 기본 값 리턴
      val result4 = runCatching { getStr() }
        .getOrDefault("기본 값")
      ```
- map
   - 응답 값을 중간에 변경할 때 사용
   - map에서 예외가 발생하면, getOrDefault 등으로 처리할 수 없다
      ```kotlin
      // 하이, 안녕하세요 리턴
      val result5 = runCatching { "하이" }
         .map { "${it}, 안녕하세요" }
         .getOrThrow()
      println(result5)
      ```
- mapCatching
   - map에서 예외가 발생할 때, catching되어서 이후 로직을 실행할 수 있도록 한다
      ```kotlin
      // 기본 값 리턴
      val result6 = runCatching { "안녕" }
        .mapCatching { throw Exception("에러") }
        .getOrDefault("기본값")
      ```
- recover
   - 에러가 발생하면 값을 복구한다
   - getOrDefault와 유사할 수 있지만, 로직을 더 넣을 수 있는 이점이 있다
      ```kotlin
      // 복구합니다 리턴
      val result7 = runCatching { getStr() }
        .recover { "복구합니다" }
        .getOrNull()
      ```
- recoverCatching
   - recover 에서 예외가 발생할 때, catching되어서 이후 로직을 실행될 수 있도록 한다
      ```kotlin
      // null 리턴
      val result8 = runCatching { getStr() }
        .recoverCatching { throw RuntimeException("test") }
        .getOrNull()
      ```